// <auto-generated />
using System;
using EfCore5MemoryTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCore5MemoryTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201120171631_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EfCore5MemoryTest.PlanItem", b =>
                {
                    b.Property<int>("PlanItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductionPlanId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.HasKey("PlanItemId");

                    b.HasIndex("ProductionPlanId");

                    b.ToTable("PlanItem");
                });

            modelBuilder.Entity("EfCore5MemoryTest.ProductionPlan", b =>
                {
                    b.Property<int>("ProductionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("ProductionPlanId");

                    b.ToTable("ProductionPlan");
                });

            modelBuilder.Entity("EfCore5MemoryTest.PlanItem", b =>
                {
                    b.HasOne("EfCore5MemoryTest.ProductionPlan", "ProductionPlan")
                        .WithMany("PlanItems")
                        .HasForeignKey("ProductionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionPlan");
                });

            modelBuilder.Entity("EfCore5MemoryTest.ProductionPlan", b =>
                {
                    b.Navigation("PlanItems");
                });
#pragma warning restore 612, 618
        }
    }
}
